version: 2.1

orbs:
  discord: sandbox/discord@dev:0.0.4

jobs:
  test_approval:
    docker:
      - image: circleci/node
    steps:
      - discord/approval:
          webhook: https://discordapp.com/api/webhooks/580466780237987870/sL59nGMtzf9goEhrq9C8CWTKbrXM7TawvnCuG_JrpdV823AnbotSdCnEbX8cgPyqipcq
  test_notify:
    docker:
      - image: circleci/node
    steps:
      - discord/notify:
          message: "Build unable to process"
          include_job_number_field: true
          include_project_field: true
          webhook: https://discordapp.com/api/webhooks/580466780237987870/sL59nGMtzf9goEhrq9C8CWTKbrXM7TawvnCuG_JrpdV823AnbotSdCnEbX8cgPyqipcq
  test_status:
    docker:
      - image: circleci/node
    steps:
      - discord/status:
          include_job_number_field: true
          include_project_field: true
          webhook: https://discordapp.com/api/webhooks/580466780237987870/sL59nGMtzf9goEhrq9C8CWTKbrXM7TawvnCuG_JrpdV823AnbotSdCnEbX8cgPyqipcq
workflows:
  version: 2
  test_all_steps:
    jobs:
      - test_approval
      - test_notify:
          requires:
            - test_approval
      - test_status:
          requires:
            - test_notify
