version: 2.1

orbs:
  discord: sandbox/discord@dev:0.0.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - discord/approval:
          webhook: https://discordapp.com/api/webhooks/580466780237987870/sL59nGMtzf9goEhrq9C8CWTKbrXM7TawvnCuG_JrpdV823AnbotSdCnEbX8cgPyqipcq
      - discord/notify:
          message: "Build unable to process"
          webhook: https://discordapp.com/api/webhooks/580466780237987870/sL59nGMtzf9goEhrq9C8CWTKbrXM7TawvnCuG_JrpdV823AnbotSdCnEbX8cgPyqipcq